apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gunicorn
  namespace: disasterkok
  labels:
    release: monitoring   # kube-prometheus-stack의 release 이름과 일치해야 Prometheus가 이 ServiceMonitor를 인식함
spec:
  selector:
    matchLabels:
      app: gunicorn        # gunicorn-svc.yaml의 selector와 동일
  namespaceSelector:
    matchNames:
      - disasterkok
  endpoints:
    - port: "8000"
      path: /metrics
      interval: 15s