alertmanager:
  enabled: false

grafana:
  enabled: true
  persistence:
    enabled: false
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false
  resources:
    requests:
      cpu: 30m
      memory: 100Mi
    limits:
      memory: 200Mi

prometheus:
  prometheusSpec:
    retention: 1d
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        memory: 400Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi