apiVersion: v1
kind: Service
metadata:
    name: gunicorn
    namespace: disasterkok
spec:
    selector:
        app: gunicorn
    ports:
        - port: 8000
          targetPort: 8000
    type: ClusterIP